"""initial schema

Revision ID: 03bd6f8ddc22
Revises:
Create Date: 2026-07-25 12:58:25.129098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03bd6f8ddc22'  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('runners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('script_content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('memory_mb', sa.Integer(), nullable=False),
    sa.Column('cpu_quota', sa.Float(), nullable=False),
    sa.Column('pids_limit', sa.Integer(), nullable=False),
    sa.Column('network_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('on_overlap', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runners_project_id'), 'runners', ['project_id'], unique=False)
    op.create_table('env_vars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_env_vars_project_id'), 'env_vars', ['project_id'], unique=False)
    op.create_index(op.f('ix_env_vars_runner_id'), 'env_vars', ['runner_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('log_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_runner_id'), 'executions', ['runner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executions_runner_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_env_vars_runner_id'), table_name='env_vars')
    op.drop_index(op.f('ix_env_vars_project_id'), table_name='env_vars')
    op.drop_table('env_vars')
    op.drop_index(op.f('ix_runners_project_id'), table_name='runners')
    op.drop_table('runners')
    op.drop_table('projects')
    # ### end Alembic commands ###
